title: Ignited Minds
theme: minima
author: Dev Ranjan Das
email: devranjandas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my effort at learning Github. So eventually I will port all my notebooks written in MarkDown using Jupyter Notebooks.

# social links
twitter_username: devranjandas
github_username:  devranjandas

show_excerpts: true # set to false to remove excerpts on the homepage
